service: thumbnail-handler

provider:
  name: aws
  runtime: nodejs8.10

functions:
  thumbnail:
    handler: handler.thumbnail
    role: arn:aws:iam::[ACCOUNT_NUMBER]:role/lambda-nanoservices
    events:     
       - sns: arn:aws:sns:us-east-1:[ACCOUNT_NUMBER]:s3-raw-images-put-topic
  