service: tags-handler

provider:
  name: aws
  runtime: nodejs8.10

functions:
  tag:
    handler: handler.tag
    role: arn:aws:iam::[ACCOUNT_NUMBER]:role/lambda-nanoservices
    events:     
      - sns: arn:aws:sns:us-east-1:[ACCOUNT_NUMBER]:s3-raw-images-put-topic